### ISSUE TITLE
대항표현 데이터를 공개하실 계획이 있나요?

### ISSUE THREAD

**Issue by mingi-sid** [hayul7805/Korean-Counter-speech#1]
안녕하세요, 굉장히 의미있는 연구 감사드립니다.

혹시 수집하신 대항표현 tsv 파일을 업로드하실 계획이 있으신가요?
앞으로의 한국어 대항표현 연구 뿐만 아니라 실제 혐오표현 대응에도 큰 도움이 될 것 같습니다.

**Comment by hayul7805** [comment]
안녕하세요, 귀한 관심 주셔서 감사합니다.
마침 논문 게재가 확정되어서 대항표현 데이터셋은 빠르면 이번 주중으로 업로드 될 예정입니다.

**Comment by mingi-sid** [comment]
감사합니다. 논문 게재 축하드립니다 :)
